# Generated by Django 5.0.6 on 2024-07-09 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='..\\static\\img\\imgUser\\', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 21, 21, 21, 467993)),
        ),
    ]
