# Generated by Django 5.0.7 on 2024-07-16 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar_alter_user_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 21, 14, 2, 191485)),
        ),
    ]
