# Generated by Django 5.0.7 on 2024-07-18 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 24, 32, 479545)),
        ),
    ]
