# Generated by Django 5.0.7 on 2024-07-19 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_date_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='imgUsers\\blankavatar.jpg', upload_to='imgUsers\\'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 12, 6, 52, 841625)),
        ),
    ]
