# fly.toml app configuration file generated for book-cit-web on 2025-04-16T12:07:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'book-cit-web'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'
console_command = '/code/manage.py shell'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'gunicorn book_cit_web.wsgi:application --bind=0.0.0.0:8000'

[[mounts]]
  source = 'media_data'
  destination = '/app/media'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
