# Generated by Django 5.0.6 on 2024-06-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=150)),
                ('book_position', models.CharField(max_length=100)),
                ('book_MFN', models.PositiveIntegerField()),
                ('book_slug', models.SlugField(blank=True)),
                ('book_publish', models.CharField(blank=True, default='No information', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.topic')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.ManyToManyField(through='home.Book_Topic', to='home.topic'),
        ),
    ]
