# Generated by Django 5.0.6 on 2024-07-09 14:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookimage_book_book_view_book_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='BM_imageURL',
            field=models.CharField(default='..\\static\\img\\imgBook\\', max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 21, 21, 21, 467993)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 21, 21, 21, 476184)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
