# Generated by Django 5.0.7 on 2024-07-16 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bookimage_bm_imageurl_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_topic',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 21, 14, 2, 191485)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 21, 14, 2, 191485)),
        ),
    ]
