# Generated by Django 5.0.7 on 2024-07-16 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_topic_id_book_topic_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_topic',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 21, 15, 27, 599700)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 21, 15, 27, 599700)),
        ),
    ]
