# Generated by Django 5.0.7 on 2024-07-16 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_book_book_topic_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_topic',
            old_name='topic',
            new_name='topic_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 22, 8, 51, 469822)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 22, 8, 51, 469822)),
        ),
    ]
