# Generated by Django 5.0.7 on 2024-07-18 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_topic_book_topic_topic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(default='imgBooks/nothumb.jpg', upload_to='imgBooks'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 24, 32, 485508)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 24, 32, 485508)),
        ),
    ]
