# Generated by Django 5.0.7 on 2024-07-19 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_bookimage_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(default='imgBooks\\nothumb.jpg', upload_to='imgBooks\\'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 9, 7, 39, 313137)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 9, 7, 39, 313137)),
        ),
    ]
