# Generated by Django 5.0.7 on 2024-08-12 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comment_created_at_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_lang',
            field=models.CharField(choices=[('Vietnamese', 'Vn'), ('Foreign', 'Fl')], default='Foreign', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 15, 1, 37, 705419)),
        ),
        migrations.AlterField(
            model_name='favlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 15, 1, 37, 706436)),
        ),
    ]
