# Generated by Django 5.0.7 on 2025-04-22 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rating_created_at_authorviewhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amazon_user_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'amazon_users',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.CreateModel(
            name='AmazonRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timestamp', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('amazon_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.amazonuser')),
            ],
            options={
                'db_table': 'amazon_ratings',
                'unique_together': {('amazon_user', 'book')},
            },
        ),
    ]
