# Generated by Django 5.0.7 on 2025-04-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_toreads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToRead',
        ),
    ]
