# Generated by Django 5.0.7 on 2025-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_isbn_10_alter_book_isbn_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
