# Generated by Django 5.0.7 on 2025-04-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_isbn_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=2250),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publish',
            field=models.CharField(blank=True, default='No information', max_length=200),
        ),
    ]
