# Generated by Django 5.0.7 on 2025-04-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_book_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=350),
        ),
    ]
