# Generated by Django 5.0.7 on 2025-04-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_book_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contentbook',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
