# Generated by Django 5.0.7 on 2025-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_book_book_title_alter_contentbook_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbook',
            name='content',
            field=models.CharField(max_length=700),
        ),
    ]
