# Generated by Django 5.0.7 on 2025-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_contentbook_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_slug',
            field=models.SlugField(blank=True, max_length=350),
        ),
    ]
