# Generated by Django 5.0.7 on 2025-05-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_bookreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_topic',
            options={'verbose_name': 'Chủ đề sách', 'verbose_name_plural': 'Các chủ đề sách'},
        ),
        migrations.AlterField(
            model_name='book_topic',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_topics', to='home.book'),
        ),
        migrations.AlterField(
            model_name='book_topic',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_books', to='home.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='book_topic',
            unique_together={('book_id', 'topic_id')},
        ),
    ]
